### ISSUE TITLE
Same "context" is returned repeatedly for every occurrence of matching string

### ISSUE THREAD

**Issue by dimitry12** [Unicity/apollo#1]
For example, when doing `apollo ./mobilehydra_log.log ab10c9e5-cb66-4a27-af27-4379dcf79ca7` I get 11 full identical requests back.

I believe, it happens because I am searching by request UUID and there are 11 events in this request.

I believe that Apollo should recognize duplicate contexts/requests and only ever return a particular context once.

**Comment by powerc9000** [comment]
Yeah I knew this would be a problem I just wanted to get the base in.
